services:
  - type: web
    name: bethel-sda-backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        value: supersecretkey
      - key: ADMIN_EMAIL
        value: admin@bethel.local
      - key: ADMIN_PASSWORD
        value: ChangeMe!234
